# Generated by Django 5.2.7 on 2026-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_kyc_rejection_reason_account_kyc_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='failed_pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='pin_lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
