# Generated by Django 5.2.7 on 2026-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_failed_pin_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='fax',
        ),
        migrations.AddField(
            model_name='kyc',
            name='mothers_maiden_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
