# Generated by Django 5.2.7 on 2026-02-09 23:33

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_kyc_fax_kyc_mothers_maiden_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=10, prefix='', unique=True),
        ),
    ]
