# Generated by Django 4.2.28 on 2026-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='business_account',
            field=models.BooleanField(default=False),
        ),
    ]
