# Generated by Django 5.2.7 on 2026-01-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
