# Generated by Django 5.2.7 on 2026-01-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_twofactorauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
