# Generated by Django 5.2.7 on 2026-01-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountfreeze',
            name='frozen_by',
        ),
        migrations.RemoveField(
            model_name='accountfreeze',
            name='unfrozen_at',
        ),
        migrations.RemoveField(
            model_name='accountfreeze',
            name='unfrozen_by',
        ),
    ]
