# Generated by Django 5.2.7 on 2026-01-19 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_accountfreeze_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfreeze',
            name='frozen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
