# Generated by Django 5.2.7 on 2026-01-19 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_kyc_rejection_reason_account_kyc_reviewed_at_and_more'),
        ('core', '0009_alter_accountfreeze_frozen_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='nickname',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_name',
            field=models.CharField(default='Paylio', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_of', to='account.account'),
        ),
    ]
