# Generated by Django 5.2.7 on 2026-01-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deposit_paymentrequest_transfer_withdrawal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
            ],
            options={
                'verbose_name': 'External Transfer',
                'verbose_name_plural': 'External Transfers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transfer',),
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
            ],
            options={
                'verbose_name': 'Internal Transfer',
                'verbose_name_plural': 'Internal Transfers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transfer',),
        ),
    ]
