# Generated by Django 5.2.7 on 2026-01-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_externaltransfer_internaltransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalTransfer',
        ),
        migrations.DeleteModel(
            name='InternalTransfer',
        ),
    ]
