# Generated by Django 5.2.7 on 2026-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_externaltransfer_delete_internaltransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
