# Generated by Django 5.2.7 on 2026-02-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_creditcard_address_line1_creditcard_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='core.creditcard'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card_payment', 'Card Payment'), ('saved_card', 'Saved Card'), ('crypto_deposit', 'Cryptocurrency Deposit')], default='bank_transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('master', 'Mastercard'), ('visa', 'Visa'), ('verve', 'Verve'), ('amex', 'American Express'), ('discover', 'Discover')], default='master', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=19),
        ),
    ]
