# Generated by Django 5.2.7 on 2026-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_creditcard_amount_deposit_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card_payment', 'Card Payment'), ('saved_card', 'Saved Card')], default='bank_transfer', max_length=50),
        ),
    ]
